import '../Place.dart';

class PlacesRepository {
  List<Place> getPlaces() {
    return [
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/uploaded-files/minaret.jpg",
        title: "Jarqo'rg'on minorasi",
        location: "Surxondaryo",
        description: "Jarqo‘rg‘on minorasi – burmalangan moʻjiza. Bir necha o‘n yillar davomida mashhur Jarqo‘rg‘on minorasi arxeologlar, tarixchilar va go‘zal arxitekturani sevuvchilarni hayratda qoldirib kelmoqda. Gap shundaki, minora noodatiy dekorativ bezak bilan bezatilgan bo‘lib, u Markaziy Osiyoda ilgari ishlatilmagan, bu bezak ko‘proq Hindistonda ishlatilgan.Minora Surxondaryo viloyatining Qumqo‘rg‘on va Termiz o‘rtasidagi Minor qishlog‘ida joylashgan. U 1109 yilda Sulton Sanjarning buyrug‘iga binoan qurilgan. Hozirda uning balandligi yigirma metrdan oshadi, ammo qurilish vaqtida u qirq uch metrga yetgan. \nMinorada uning yaratuvchisi, Seraxs shahridan usta Ali ibn Muhammadning ismini va undan yuqoriroq qismida esa, oxiriga yetkazilmagan Qurʼonning muqaddas suralarini ko‘rish mumkin. Minoraning siljigan o‘qi tufayli u tugallanmagan yoki qisman vayron bo‘lgan deb taxmin qilinadi. 1879 yilda minora yaqinida qadimiy masjidning xarobalari topilgan, bu minora qurilishi alohida amalga oshirilganidan dalolat beradi. Minoraga nima bo‘lganligi va nima uchun masjid vayron qilinganligi to‘g‘risida tarixchilar bir fikrga kela olishmadi. Ehtimol, yangi bino qurish uchun binolar qasddan buzilgandir.Minoraga qarab, uning bezaklaridan ko‘zingizni uzolmaysiz. G‘ishtlarning mahorat bilan archa naqshida terilganligi to‘qilganlik effektini yaratadi. Minoraning ostida turganingizda, g‘ishtlarning terilgani g‘isht emas, balki mato kabi ko‘rinadi. Minora bir-biriga ulashgan o‘n olti yarim ustundan iborat. Ichkarida aylanali zinapoyalar mavjud bo‘lib, ular bo‘ylab eng yuqoriga ko‘tarilish mumkin. Hozirda Jarqo‘rg‘on minorasi ehtiyotkorlik bilan qo‘riqlanadi va muhim tarixiy va madaniy obyekt hisoblanadi.",
        id: "Surxondaryo",
        lat: 37.476849,
        long: 67.3961932
      ),
      Place(
        imageUrl: "https://lp-cms-production.imgix.net/2023-07/GettyImages-1193462464.jpg?fit=crop&w=1920&auto=format&q=75",
        title: "Eski shahar",
        location: "Buxoro",
        description: "Qadimgi Buxoro islom madaniyati va O‘zbekistonning qadimiy tarixi markazidir. Bu shahar oʻzining ikki ming yillik tarixi davomida buyuk tarixiy voqealarga, ayovsiz qonli janglarga guvoh boʻlgan. Bu janglardan biri 1511-1512-yillarda Temuriy Bobur qo‘shinlari va o‘zbek xoni Shayboniyxon o‘rtasida bo‘lib o‘tgan. 1512-yil noyabr oyida Gʻijduvon yaqinida oʻzbek qoʻshinlari Muhammad Boburning birlashgan qoʻshinini magʻlub etadi. G‘ijduvon jangi g‘olibi, Muhammad Shayboniyxonning jiyani, Qur’oni karim bilimdoni, iste’dodli shoir, olimlar homiysi Ubaydullaxon Buxoro hukmdori etib tayinlandi. Aynan Ubaydullaxon davrida Buxoro gullab-yashnadi, shahar o‘ziga xos me’moriy uslubga ega bo‘ldi. 1514-yilda Kalom jome masjidi qayta tiklandi, u Qoraxoniy Arslonxon davrida qurilgan (1102-1130), 1404-yilgacha Movarounnahrdagi eng yiriklaridan biri, Samarqandda Temurning nabirasi tomonidan qurilgan Bibi-Xonim masjidi Ulug‘bek tomonidan tugallangan. Ubaydullaxonning buyrug‘i bilan masjidning old qismi katta peshtoq bilan bezatilgan va yangi mehrob o‘rnatilgan.1530-yilda Bibixonim masjididan uncha uzoq boʻlmagan joyda Samarqanddagi Ulugʻbek madrasasidan kattaroq boʻlgan Miri Arab madrasasi qurilishi boshlandi. Yangi madrasa Yamanda tug‘ilgan arab olimi, nufuzli naqshbandiy shayx Xo‘ja Axrarning shogirdi va Ubaydulloxonning ruhiy ustozi Amir Abdulloh al-Yamaniy sharafiga nomlangan.Miri Arab madrasasi bugungi kunda Kalon masjidi va minorasini hamda Amir Olimxon madrasasini o‘z ichiga olgan Poyi-Kalon me’moriy ansamblining bir qismidir. Madrasaning old qismi Kalon minorasi tomonga qaragan. Madrasaga kiraverish ulug‘vor va chuqur bezatilgan peshhtoq bilan bezatilgan, o‘zining old tomonida ulkan minoralari joylashgan.Agar siz o‘ng tomondagi markaziy kirishdan kirsangiz, Shayx Abdulla al-Yamaniyning marmar qabrini va Ubaydulloxon dafn qilingan joyni ko‘rishingiz mumkin. Binolar ko‘k plitalar bilan qoplangan ikkita gumbaz bilan qo‘riqlanadi.",
        id: "Buxoro",
        lat: 39.7758131,
        long: 64.4154574,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/citys/5e53c06ca0049049451193.jpg",
        title: "Tashkent City",
        location: "Toshkent",
        description: "Toshkent shahri – O‘zbekistonning poytaxti bo‘lib, uning boy tarixi va zamonaviy rivojlanishi birlashtirilgan noyob madaniy markaz sifatida ajralib turadi. Shaharda qadimgi tarixiy yodgorliklar, zamonaviy arxitektura va keng xiyobonlar, bog‘lar uyg‘unlashgan bo‘lib, bu uning ko‘p qirrali hayot tarzini aks ettiradi. Toshkent ko‘chalari, savdo markazlari, teatrlar, muzeylar va madaniyat institutlari shaharning iqtisodiy va madaniy hayotini jonlantiradi, shu bilan birga, innovatsion loyihalar va zamonaviy transport tizimi orqali kelajakka qadam qo‘yish imkoniyatini yaratadi. Bu shahar o‘zining tarixiy ildizi, milliy an’analar va tez rivojlanayotgan infratuzilmasi bilan nafaqat yurt ichida, balki mintaqaviy miqyosda ham muhim ahamiyatga ega ekanligini ko‘rsatadi.",
        id: "Toshkent",
        lat: 41.316366,
        long: 69.2462061,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/noviy/mechet-minor-2020-kopiya.jpg",
        title: "Minor masjidi",
        location: "Toshkent",
        description: "Minor masjidi – Toshkentning diniy va madaniy merosida o‘ziga xos o‘rin egallagan, qadimiy tarix va nafis me’morchilik namunalarini aks ettiruvchi muqaddas inshootdir. Ushbu masjidning go‘zal arxitekturasi, o‘ziga xos bezaklari va minora tizimi musulmon me’morchiligining boy an’analarini aks ettiradi. Minor masjidi nafaqat ibodatlar uchun markaz sifatida xizmat qiladi, balki tarixiy voqealar va madaniy tadbirlar orqali mahalliy aholi hamda sayyohlarni o‘ziga jalb etadi. Uning ichki makoni va tashqi ko‘rinishi, an’anaviy naqshinkorlik bilan zamonaviy dizayn elementlarini uyg‘unlashtirgan holda, diniy e’tiqod va san’atning uyg‘onishining yorqin namunasi hisoblanadi.",
        id: "Toshkent",
        lat: 41.3353102,
        long: 69.2724601,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/uploaded-files/P6247139b.jpg",
        title: "Xiva qadimiy shahri",
        location: "Xiva",
        description: "Xiva qadimiy shahri – Markaziy Osiyoning eng noyob tarixiy yodgorliklaridan biri bo‘lib, o‘zining boy arxitekturasi, qadimiy devorlari va madaniy an’analari bilan ajralib turadi. Bu shahar qadimiy savdo yo‘llari va karvonsaroylar orqali mintaqaviy savdo va madaniyat almashinuvi markazi bo‘lgan. Xivaning yuragi hisoblangan Ichan-Qal’a, o‘zining qalin devorlari, masjidlar, madrasalar va maqbaralari bilan shaharning tarixiy merosini saqlab qolgan. Tarixiy inshootlar va tor-ko‘cha labirintlari orqali sayyohlar shaharning o'tmishi, qadimiy hayot tarzi va san’atining nozik namunalarini his etishlari mumkin. Xiva qadimiy shahri o‘zining ma’naviyati va tarixiy boyliklari bilan zamonaviy dunyoda ham e’tirof etilib, tarix ixlosmandlari va sayyohlar uchun qimmatli ilmiy va madaniy manba sifatida xizmat qiladi.",
        id: "Xorazm",
        lat: 41.3891392,
        long: 60.3088036,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/Otabek/asosiydagi%20rasmlar/cropped-images/2T0A0390-0-0-0-0-1728557400.jpg",
        title: "Zomin tabiati",
        location: "Jizzax",
        description: "Zomin tabiati o‘zining betakror landshaftlari, tog‘lari, o‘rmonlari va keng yaylovlari bilan ajralib turadi. Hududdagi tog‘ cho‘qqilari va pastliklar orasida oqayotgan daryo va shoxobchalar, yashil o‘rmonlar hamda tabiatning turli xil rang-barangligi insonlarga dam olish, ilhom olish va tinchlik topish imkonini beradi. Bu yerda noyob o‘simlik va hayvon turlari uchraydi, shuningdek, mahalliy aholining tabiatni asrab-avayishdagi mehnati, ekologik muvozanatni saqlashga qaratilgan choralari seziladi. Zominning tabiiy go‘zalligi nafaqat mahalliy turizm va dam olish maskani sifatida, balki ekologik resurslarni o‘rganish va saqlash nuqtai nazaridan ham katta ahamiyatga ega.",
        id: "Jizzax",
        lat: 39.9623513,
        long: 68.3909738,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/uploaded-files/samarkand-uzbekistan-kupol-mechet-ploshchad.png",
        title: "Registon maydoni",
        location: "Samarqand",
        description: "Registon maydoni Samarqandning yuragi bo‘lib, unda uchta ulkan madrasalar joylashgan. Bu joy tarixiy obidalari va go‘zalligi bilan mashhur.",
        id: "Samarqand",
        lat: 39.654867,
        long: 66.9730413,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/uploaded-files/photo_2024-07-01_12-11-20.jpg",
        title: "Ko‘ksaroy saroyi",
        location: "Shahrisabz",
        description: "Ko‘ksaroy saroyi – qadimiy davrlar merosidan qolgan noyob arxitektura yodgorligi bo‘lib, u o‘zining nafis naqshinkorligi, boy bezaklari va tarixiy ahamiyati bilan ajralib turadi. Ushbu saroy tarixiy hukmdorlar davrida qurilgan bo‘lib, o‘sha davrning siyosiy, madaniy va ijtimoiy hayotining guvohi sifatida xizmat qiladi. Saroyning ichki makonidagi marvarid, yog‘och va sopol bezaklar, devor va shiftlardagi nafis naqshlar, keng hovli va bog‘lar uni san’at va me’morchilikning yuqori namunasi sifatida namoyon etadi. Ko‘ksaroy saroyi nafaqat tarixiy voqealar va madaniy an’analarni aks ettiruvchi inshoot, balki mahalliy merosni saqlab qolish va kelajak avlodlarga etkazishda muhim rol o‘ynaydi. Ushbu inshoot tarixshunoslar, san’at ixlosmandlari va sayyohlar uchun ilhom manbai bo‘lib, uning go‘zalligi va zamonaviylik bilan uyg‘unlashgan tarixi doimo e’tirof etiladi.",
        id: "Qashqadaryo",
        lat: 39.0538246,
        long: 66.6336156,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/IMG_8988-0-0-0-0-1591786142.jpg",
        title: "Yozuvchilar xiyoboni",
        location: "Toshkent",
        description: "Daraxtlar va gulzorlar orasida sayr qilish uchun va albatta gavjum shahar markazida o‘ziga xos atmosferani yarat o‘zida jamlagan ajoyib maskan. Oʻzbek adabiyotining “otasi” hisoblangan Alisher Navoiy boshchiligidagi bronza yodgorliklari 8 gektardan ortiq maydonni egallagan yagona va betakror meʼmoriy ansamblni tashkil etadi. Ilgari bog‘da o‘zbek adabiyotining ayrim adiblariga haykallar o‘rnatilgan bo‘lsa, yirik madaniy-ma’rifiy markaz yaratish maqsadida 20 dan ortiq adabiyot arboblari, jumladan, yozuvchi va shoirlar, tanqidchi va publitsistlar: Bobur, Muhammad Rizo Ogaxiy, Zokirjon Furqat, Muhammad Aminxo‘ja Muqimiy, Mahmudxo‘ja Behbudiy, Berdaq, Abdulla Avloniy, Abdulhamid Cho‘lpon, Abdulla Qodiriy, Abdulla Qahhor va boshqa yetuk insonlar haykallari qad rostlagan. Adiblar xiyoboni ijodiy kechalar, mushoiralar, kitob taqdimotlari, ko‘rgazmalar o‘tkaziladigan maskanga aylandi. O‘zbek adabiyoti kundalik hayotimizning ajralmas qismiga aylanishi kerak, chunki zamonaviy voqelikda yoshlar o‘zbek adabiyoti klassiklariga tobora kamroq murojaat qilmoqda.",
        id: "Toshkent",
        lat: 41.3034246,
        long: 69.2328057,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/2-0-0-0-0-1583391101.jpg",
        title: "Temuriylar tarixi muzeyi",
        location: "Toshkent",
        description: "Mashhur Temuriylar tarixi muzeyi - Toshkentning diqqatga sazovor joylari sirasiga kirib, sayohatchilarning diqqat markazida turadi. U 1996- yilda butun dunyo bo‘ylab taniqli bo‘lgan buyuk sarkarda Amir Temur tavalludining 660 yilligi sharafiga ochilgan. Muzeyning uch qavatli yumaloq binosi gumbaz bilan klassik sharqona uslubda bezatilgan. Binoning ichki qismi marmar, noyob rasmlar, betakror naqshlar va oltin suvi bilan bejirim bezatilgan. Zallar devorlarida Amir Temurning hayoti, shuningdek o‘sha davrlarning atmosferasini aks ettiruvchi rasmlar freska tarzida aks etgan. Muzeyning eng maftunkor qismi - balandligi 8,5 metr bo‘lgan billur qandil bo‘lib, undagi 106 ming marjon ko‘zlarni qamashtiradi. Muzey eksponatlari tashrif buyuruvchilarga Temuriylar sulolasi davrida O‘zbekiston tarixi haqida ma’lumot beradi. Muzey fondida 3 mingdan ortiq eksponatlar mavjud. Bu yerda o‘rta asrlarga oid zargarlik buyumlarini, kiyim-kechaklarni, musiqa asboblari, mehnat anjomlari va boshqa buyumlarni ko‘rishingiz mumkin. Musulmonlarning muqaddas kitobi bo‘lgan Usmonning Qur’on nusxasi markaziy zalda saqlanadi. Muzey ekspozitsiyasida Amir Temur va uning avlodlarining Yevropa mamlakatlari monarxlari bilan bo‘lgan ko‘plab yozishmalari, buyuk sarkarda tasvirlangan rasmlar, miniatyuralar, mamlakatimizda Temuriylar sulolasi tomonidan qurilgan mashhur inshootlarning maketi joy olgan.",
        id: "Toshkent",
        lat: 41.313626,
        long: 69.2763819,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/Otabek/skver/cropped-images/dji0192-2-0-0-0-0-1663329685.jpg",
        title: "Mustaqillik maydoni",
        location: "Toshkent",
        description: "Bu nafaqat Toshkentning, balki butun O‘zbekistonning asosiy maydonidir. Katta va keng, qalin ko‘kalamzor bilan o‘ralgan va son-sanoqsiz favvoralar bilan bezatilgan maydon ikkita tarixiy markazni - Eski shahar va Toshkentning yangi qismini birlashtiradi. Maydonning markazida “Mustaqillik va ezgulik” yodgorligi o‘rnatilgan bo‘lib, uning ustiga milliy suverenitetimizni dunyo tomonidan tan olinishining ramzi sifatida respublikamiz hududi o‘yib tushirilgan sayyora tasvirlangan bronza shar o‘rnatilgan. Pastki qismida esa –“Baxtiyor ona” haykali. Mehribon yuzli va ko‘zlari baxtdan porlagan oddiy o‘zbek ayoli Vatan, hayot va donishmandlik timsolidir. U o‘zining bebaho xazinasini ehtiyotkorlik bilan ushlab turibdi va farzand ishonchli qo‘llarda. Yodgorlik tinchlik, farovon hayot, baxtli kelajakka ishonch hamda hozirgi va kelgusi avlodlar uchun baxtni anglatadi. Bu, shuningdek, demokratiya va erkin fuqarolik jamiyatini barpo etayotgan, inson huquqlari va manfaatlarini ustuvor deb e’lon qilgan mamlakatda ayollarga bo‘lgan cheksiz hurmatning ifodasidir. Shuningdek, yurtimizga tashrif buyuradigan xorijiy mamlakatlarning rahbarlari, delegatsiyalar va mehmonlar ham Monument poyiga gulchambar qo‘yib, mustaqil O‘zbekistonimizga hurmatini ifoda etadi. Ushbu yodgorlik bilan bir qatorda Ezgulik arkasi - yaxshi va ezgu intilishlar yoyi joylashgan.",
        id: "Toshkent",
        lat: 41.3152564,
        long: 69.264052,
      ),
      Place(
        imageUrl: "https://uzbekistan.travel/storage/app/media/nargiza/cropped-images/SitoraiMokhi-hosa-0-0-0-0-1588315287.jpg",
        title: "Sitorai Mohi Xosa",
        location: "Buxoro",
        description: "Buxoroning to‘rt kilometr shimolida ajoyib betakror saroy joylashgan. Bu qarorgohda o‘z vaqtida mang‘itlar sulolasidan bo‘lgan Buxoro amiri – Amir Said Olimxon (1911-1920) yashagan. Afsuski, Rossiya qo‘shinlarining Buxoroga bostirib kirishi tufayli Amir saroyni tashlab Afg‘onistonga qochishga majbur bo‘lgan. Qarorgoh ikki qismga – eski (sharqona) va yangi (Yevropa uslubidagi) bo‘linadi. Qadimgi saroy XVIII asrda, yangi qismi esa XX asr boshida qurilgan. Qurilishda nafaqat mahalliy, balki rus me’morlari ham ishtirok etgan. Saroy erkaklar va ayollar uchun alohida qismlarga ega. Saroyga kiraverishda hashamatli darvoza, saroy o‘rtasida hovuz, tomlar ustidagi dekorativ vazalar, feruza rangli ayvonlar, va sher haykallari joylashgan. Qarorgoh nomi “Oyga o‘xshash Yulduz” degan ma’noni anglatadi.",
        id: "Buxoro",
        lat: 39.8141969,
        long: 64.4385364,
      ),
    ];
  }
}
